### ISSUE TITLE
ACDC albums are all renamed as DC

### ISSUE THREAD

**Issue by dbenyakar** [plexinc-agents/LastFM.bundle#17] opened 2015-02-03 05:16 UTC
I have this problem where all my ACDC albums appear as DC. This is in Plex and Last.fm is the agent.

Im using the same music folder structure for all of my library: \A\ACDC(1975) T.N.T, and my Artist matches Album Artist, and Im using MP3Tag to tag all my music.

I changed all the ACDC albums metadata to ACDC, re-scanned my library and no change. All albums show as DC. 
Then I renamed it all as AC/DC to match the name that appears in LastFM, scanned my library and it seems to initially pick the albums names correctly but then it renames them again to be DC.

**Comment by mmccurdy07** [comment] 2015-02-03 05:23
Dupe of #14 (which I had not noticed until you commented earlier today).  I'll take a look.

**Closed by mmccurdy07** 2015-02-03 05:23 UTC

**Comment by PEMAMETAL** [comment] 2015-11-21 21:17
I am having the same exact issue. Plex start to search and everything seems ok, the album art is correct. Suddenly the albums name start to change to DC and the album art becomes all the same. How can I fix this?
